s=set()
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
s=set(map().split())
print(s)